* NaoText Syntax Definition *

Program ::= Robots Collaborations
Robots ::= Robot ";" {Robot ";"}
Robot ::= "CPS" Name "IP" Ip "PORT" Port
Name ::= String
RoleName ::= String
Ip ::= 1{Digit}3 "." 1{Digit}3 "." 1{Digit}3 "." 1{Digit}3
Digit ::= "0" | ... | "9"
Port ::= Digit {Digit}
Collaborations ::= Collaboration {Collaboration}
Collaboration ::= "context" Name
					"{"
						{ [VariableDecls | Collaboration | Roles | Constraints | ActivationRule] }
					"}"
Variable ::= String
VariableDecls ::= VariableDecl ";" {VariableDecl ";"}
VariableDecl ::= EVariableDecl | IVariableDecl
EVariableDecl ::= ["var" | "val"] Variable ":" Type
IVariableDecl ::= EVariableDecl "=" Value
Type ::= String
Value ::= String
Constraints ::= Constraint ";" {Contraint ";"}
Constraint ::= RoleName ["equals" | "implies" | "prohibits"] RoleName
ActivationRule ::= "activate for"
					"{"
						RoleName Variable ";" {RoleName Variable ";"}
					"} when {" JavaCode "}"
					"with bindings"
					"{"
						Variable "->" RoleName ";" {Variable "->" RoleName ";"}
					"}"
Roles ::= Role {Role}
Role ::= "role" Name "{" Behavior {VariableDecls|Methods} "}"
JavaCode ::= String
Methods ::= Method {Method}
Method ::= JavaCode
Behavior ::= "behavior {" JavaCode "}"