/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.aldebaran.proxy;

public class ALProxy {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ALProxy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ALProxy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNaoQiJNI.delete_ALProxy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ALProxy(String moduleName, String ip, int port) {
    this(JNaoQiJNI.new_ALProxy(moduleName, ip, port), true);
  }

  public Variant call(String method) {
    return new Variant(JNaoQiJNI.ALProxy_call__SWIG_0(swigCPtr, this, method), true);
  }

  public Variant call(String method, Variant val) {
    return new Variant(JNaoQiJNI.ALProxy_call__SWIG_1(swigCPtr, this, method, Variant.getCPtr(val), val), true);
  }

  public Variant call(String method, Variant val1, Variant val2) {
    return new Variant(JNaoQiJNI.ALProxy_call__SWIG_2(swigCPtr, this, method, Variant.getCPtr(val1), val1, Variant.getCPtr(val2), val2), true);
  }

  public Variant call(String method, Variant val1, Variant val2, Variant val3) {
    return new Variant(JNaoQiJNI.ALProxy_call__SWIG_3(swigCPtr, this, method, Variant.getCPtr(val1), val1, Variant.getCPtr(val2), val2, Variant.getCPtr(val3), val3), true);
  }

  public Variant call(String method, Variant val1, Variant val2, Variant val3, Variant val4) {
    return new Variant(JNaoQiJNI.ALProxy_call__SWIG_4(swigCPtr, this, method, Variant.getCPtr(val1), val1, Variant.getCPtr(val2), val2, Variant.getCPtr(val3), val3, Variant.getCPtr(val4), val4), true);
  }

  public Variant call(String method, Variant val1, Variant val2, Variant val3, Variant val4, Variant val5) {
    return new Variant(JNaoQiJNI.ALProxy_call__SWIG_5(swigCPtr, this, method, Variant.getCPtr(val1), val1, Variant.getCPtr(val2), val2, Variant.getCPtr(val3), val3, Variant.getCPtr(val4), val4, Variant.getCPtr(val5), val5), true);
  }

  public Variant call(String method, Variant val1, Variant val2, Variant val3, Variant val4, Variant val5, Variant val6) {
    return new Variant(JNaoQiJNI.ALProxy_call__SWIG_6(swigCPtr, this, method, Variant.getCPtr(val1), val1, Variant.getCPtr(val2), val2, Variant.getCPtr(val3), val3, Variant.getCPtr(val4), val4, Variant.getCPtr(val5), val5, Variant.getCPtr(val6), val6), true);
  }

}
