/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

 package com.aldebaran.proxy;

public class SWIGTYPE_p_AL__ALValue {
  private long swigCPtr;

  protected SWIGTYPE_p_AL__ALValue(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_AL__ALValue() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_AL__ALValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

